name: Setup Flutter Environment
description: Common Flutter project preparation used across CI jobs

inputs:
  java-version:
    description: Java version to install
    required: false
    default: "17"
  flutter-channel:
    description: Flutter channel to install
    required: false
    default: "stable"
  fetch-depth:
    description: Git fetch depth for checkout
    required: false
    default: "1"
  submodule-token:
    description: Access token used for private submodules
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Try to checkout submodules
      shell: bash
      continue-on-error: true
      run: |
        echo "Attempting to checkout submodules..."
        if [ -n "${{ inputs.submodule-token }}" ]; then
          echo "Using provided submodule token for authentication"
          git config --global url."https://x-access-token:${{ inputs.submodule-token }}@farheapsolutions.visualstudio.com/".insteadOf "https://farheapsolutions.visualstudio.com/"
        fi
        git submodule update --init --recursive || echo "⚠️ Submodule checkout failed (expected without access token)"

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java-version }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ inputs.flutter-channel }}
        cache: true

    - name: Install dependencies
      shell: bash
      run: flutter pub get
